export type CurrencyOption = {
  code: string;
  label: string;
};

/** Common and regional currencies for WorkBridge payments (ISO 4217 codes). */
export const CURRENCY_OPTIONS: readonly CurrencyOption[] = [
  { code: "USD", label: "USD — US Dollar" },
  { code: "EUR", label: "EUR — Euro" },
  { code: "GBP", label: "GBP — British Pound" },
  { code: "JPY", label: "JPY — Japanese Yen" },
  { code: "CHF", label: "CHF — Swiss Franc" },
  { code: "CAD", label: "CAD — Canadian Dollar" },
  { code: "AUD", label: "AUD — Australian Dollar" },
  { code: "NZD", label: "NZD — New Zealand Dollar" },
  { code: "SEK", label: "SEK — Swedish Krona" },
  { code: "NOK", label: "NOK — Norwegian Krone" },
  { code: "DKK", label: "DKK — Danish Krone" },
  { code: "PLN", label: "PLN — Polish Złoty" },
  { code: "CZK", label: "CZK — Czech Koruna" },
  { code: "HUF", label: "HUF — Hungarian Forint" },
  { code: "RON", label: "RON — Romanian Leu" },
  { code: "BGN", label: "BGN — Bulgarian Lev" },
  { code: "ISK", label: "ISK — Icelandic Króna" },
  { code: "TRY", label: "TRY — Turkish Lira" },
  { code: "RUB", label: "RUB — Russian Ruble" },
  { code: "UAH", label: "UAH — Ukrainian Hryvnia" },
  { code: "BYN", label: "BYN — Belarusian Ruble" },
  { code: "MXN", label: "MXN — Mexican Peso" },
  { code: "BRL", label: "BRL — Brazilian Real" },
  { code: "ARS", label: "ARS — Argentine Peso" },
  { code: "CLP", label: "CLP — Chilean Peso" },
  { code: "COP", label: "COP — Colombian Peso" },
  { code: "PEN", label: "PEN — Peruvian Sol" },
  { code: "UYU", label: "UYU — Uruguayan Peso" },
  { code: "ZAR", label: "ZAR — South African Rand" },
  { code: "NGN", label: "NGN — Nigerian Naira" },
  { code: "KES", label: "KES — Kenyan Shilling" },
  { code: "EGP", label: "EGP — Egyptian Pound" },
  { code: "MAD", label: "MAD — Moroccan Dirham" },
  { code: "GHS", label: "GHS — Ghanaian Cedi" },
  { code: "AED", label: "AED — UAE Dirham" },
  { code: "SAR", label: "SAR — Saudi Riyal" },
  { code: "QAR", label: "QAR — Qatari Riyal" },
  { code: "KWD", label: "KWD — Kuwaiti Dinar" },
  { code: "BHD", label: "BHD — Bahraini Dinar" },
  { code: "OMR", label: "OMR — Omani Rial" },
  { code: "ILS", label: "ILS — Israeli Shekel" },
  { code: "JOD", label: "JOD — Jordanian Dinar" },
  { code: "LBP", label: "LBP — Lebanese Pound" },
  { code: "INR", label: "INR — Indian Rupee" },
  { code: "PKR", label: "PKR — Pakistani Rupee" },
  { code: "BDT", label: "BDT — Bangladeshi Taka" },
  { code: "LKR", label: "LKR — Sri Lankan Rupee" },
  { code: "NPR", label: "NPR — Nepalese Rupee" },
  { code: "THB", label: "THB — Thai Baht" },
  { code: "SGD", label: "SGD — Singapore Dollar" },
  { code: "MYR", label: "MYR — Malaysian Ringgit" },
  { code: "IDR", label: "IDR — Indonesian Rupiah" },
  { code: "PHP", label: "PHP — Philippine Peso" },
  { code: "VND", label: "VND — Vietnamese Dong" },
  { code: "KHR", label: "KHR — Cambodian Riel" },
  { code: "MMK", label: "MMK — Myanmar Kyat" },
  { code: "KRW", label: "KRW — South Korean Won" },
  { code: "TWD", label: "TWD — Taiwan Dollar" },
  { code: "HKD", label: "HKD — Hong Kong Dollar" },
  { code: "CNY", label: "CNY — Chinese Yuan" },
  { code: "MOP", label: "MOP — Macanese Pataca" },
] as const;
